#!/bin/bash
(cd ~/projects &&  git clone git@gitlab.com:mitimes/timesheets4.git)

(cd ~/projects && git clone git@gitlab.com:mitimes/miexchange.git)
(cd ~/projects && git clone git@gitlab.com:mitimes/exchangewatch-t4.git)

(cd ~/projects && git clone git@gitlab.com:mitimes/datacollector2.git)
(cd ~/projects && git clone git@gitlab.com:mitimes/MitimesDataCollector.git)

(cd ~/projects && git clone git@gitlab.com:mitimes/compliance_portal.git)

(cd ~/projects && git clone git@gitlab.com:mitimes/worksite-integration.git)
