#!/bin/bash
# As per: https://www.atlassian.com/git/tutorials/dotfiles


# Is already added to bash alias in dotfiles repo
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
git clone --bare git@github.com:adz/dotfiles.git
config config --local status.showUntrackedFiles no

# Can fail if files exist already (probably will)
# Remove or backup offending files first
config checkout
