#!/bin/bash

# TRIM helps use SSD more efficiently and extend it's life
sudo systemctl enable fstrim.timer

./uninstall_crap
./install_apps

./configure_git

./install_docker

./clone_projects

./asdf_dependencies
./asdf_install

# Tools (put on path)
mkdir -p ~/tools/bin

# eb cli tool
(cd ~/tools && git clone git@github.com:adz/awsebcli_docker)
ln -s ~/tools/awsebcli_docker/eb ~/tools/bin/eb


