#!/bin/bash

# TRIM helps use SSD more efficiently and extend it's life
sudo systemctl enable fstrim.timer

./uninstall_crap
./install_apps

./configure_git

./install_docker

./clone_projects

./asdf_dependencies
./asdf_install


